DROP TABLE IF EXISTS ISINS;
CREATE TABLE ISINS
(
    ID UUID PRIMARY KEY NOT NULL,
    ISIN VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS QOUTES;
CREATE TABLE QOUTES
(
    ID UUID PRIMARY KEY NOT NULL,
    ISIN UUID NOT NULL,
    BID FLOAT(5),
    ASK FLOAT(5),
    STMP TIMESTAMP NOT NULL,

    FOREIGN KEY (ISIN) REFERENCES ISINS(ID)
);

DROP TABLE IF EXISTS ELVLS;
CREATE TABLE ELVLS
(
    ID UUID PRIMARY KEY NOT NULL,
    ISIN UUID NOT NULL,
    ELVL FLOAT (5) NOT NULL,

    FOREIGN KEY (ISIN) REFERENCES ISINS(ID)
);

